### ISSUE TITLE
accessToken validity issues

### ISSUE THREAD

**Issue by TheDogHusky** [slekup/passport-discord-auth#21]
Hello!

I'm making a website for a friend, and I used passport-discord before. I saw that it wasn't maintained and switched here.
I'm using a mongoDB database with Mongoose ORM to manage user profiles and accounts.
However, I've came accross an issue:
The accessToken validity is not checked dynamically.

This causes the following problem:
A user with an invalid token can still travel around the website, including the dashboard. That means someone can inject an invalid token in his session and be able to access everything he wants? (idk)
A user that wants to send a message to an opened ticket won't be able to do so, as for the API, I use the accessToken to retrieve user information and ensure he is logged in correctly.

Any ideas ?

**Comment by slekup** [comment]
Could you elaborate on what you mean by "checked dynamically"?

When the user authenticates with Discord, your API gets access to the user's discord information that it has access to and should create a `accessToken` and `refreshToken`. That information should be stored locally or, more commonly, in a database. For all your authenticated routes, you should be using the `passport.authenticate()` method, as long as you have that, it won't allow any invalid access tokens to give a user access to those routes.

**Comment by TheDogHusky** [comment]
The thing is like using passport.authenticate on all routes that requires authentication would be kinda.. weird? As it is better to just have the /login route authenticate the user then use connect-ensure-login to prevent people with invalid tokens to access routes.
The problem I saw is that connect-ensure-login uses the isAuthenticated function/property which doesn’t check the token validity, and only checks for a .user property.

What I meant my checking the token dynamically is to ensure that every time a user accesses a route that requires authentication, it should be logged in and with a valid token.

**Comment by slekup** [comment]
> The thing is like using passport.authenticate on all routes that requires authentication would be kinda.. weird?

Why is that weird? You add it as [middleware](https://www.passportjs.org/concepts/authentication/middleware/) to a route such as `/api/dashboard` so all endpoints under that route require authentication.

> The problem I saw is that connect-ensure-login uses the isAuthenticated function/property which doesn’t check the token validity, and only checks for a .user property.

Assuming you mean the package, I've never seen it before and it looks like it hasn't been updated in 11 years. I wouldn't recommend using packages that old. Regardless, in most cases. your `passport.deserializeUser()` is run every time a request is received, thus as long as the token provided by the user is valid, then there will be a valid `req.user`.

Authentication is difficult to implement and maintain, so I wouldn't recommend doing anything other than what's provided by the authentication libraries like passport.

**Comment by TheDogHusky** [comment]
That's the issue: `passport.deserializeUser()` is ran in every requests, but the token was invalid, allowing the user to go inside of the dashboard even if he shouldn't be able to do it.

**Comment by slekup** [comment]
> That's the issue: passport.deserializeUser() is ran in every requests, but the token was invalid, allowing the user to go inside of the dashboard even if he shouldn't be able to do it.

Why is the token invalid? Can you make a repro?

> As for the weird thing, it's that every website I ever seen just redirects the user to the /login route when they are not logged in, with a redirect URL to put the user back in the path he was browsing on. Also, every boilerplate or example I looked up on Github that uses passport never used the authenticate middleware somewhere else than in the login route.

What's the difference with the example provided here?

**Comment by TheDogHusky** [comment]
I took a look at the example on this repo, and I don't see a lot of differences to my current setup. The serialize and deserialize user functions function the same, with not that much differences. I you want to see the functions:
```ts
passport.serializeUser((user, done) => {
    done(null, user);
});

passport.deserializeUser(async (obj: IUser, done) => {
    const user = await User.findOne({ id: obj.id }).catch(err => {
        done(err, null);
    });
    if(user) {
        if(user.disabled) {
            done(new Error('Account is disabled'), null);
        } else {
            done(null, user);
        }
    } else {
        done(null, null);
    }
});
```

As for the repro, how do you want me to do it? Do I need to make a repo with the repro? As I don't think codepen or other services like so supports expressjs and nodejs webservers.
Also this website is a private repo as it is a paid job that I do.

**Comment by slekup** [comment]
If it's the same, I'm not sure what the issue is.

**Comment by TheDogHusky** [comment]
One thing is sure, i cannot release this website publicly before figuring out the issue and fixing it.

**Comment by slekup** [comment]
Did you try it with middleware that checks if the user property exists on the req object?

Is your frontend requesting a new access token because it's invalid, by providing the refresh token? (should be how it works, so when you say you're changing your token, it should be both the refresh and access tokens)

Try debugging each step in your app to see exactly where things go wrong.

**Comment by TheDogHusky** [comment]
User property did exist, but the `accessToken` property gave an invalid token.
I'm not using the refresh token, i want that if the token is invalid the user just has to log back in, as I don't want infinite sessions, and the longevity of the token is enough for me.

**Comment by slekup** [comment]
The `accessToken` property from the `req` object gave an invalid token. Is this after you sent a request _using_ an invalid access token?

**Comment by TheDogHusky** [comment]
I logged in, got my token, it is valid, i can do requests using it.
After some time, it becomes invalid, still stored in the database and session, which now gives me errors while making requests, but still allows me to navigate on the website even though it should log me out as it is invalid.

**Comment by slekup** [comment]
It sounds like an implementation issue. I'm honestly not sure how to address what you're asking.

**Comment by TheDogHusky** [comment]
If you don’t understand the issue then i cannot explain it more clearly than with a video and diagrams, which i cannot do.
Thanks for your help.

**Comment by slekup** [comment]
I understand the issue, I'm just not sure how to address it since I haven't seen a situation where I get the same result. Sorry I couldn't help, but feel free to make a fork. Aside from the types, the code is pretty minimal.
