### ISSUE TITLE
Feature Request: Support for oauth2 state

### ISSUE THREAD

**Issue by kaine-adams** [slekup/passport-discord-auth#22]
Discord (and many oauth) support the parameter state, for returning the user to a previous state. This is useful when binding accounts/users.

Is it possible to get this added?

https://discord.com/developers/docs/topics/oauth2#state-and-security

Thanks!

**Comment by slekup** [comment]
Hi, sorry for the late response. I haven't used this before, does this not work?
![image](https://github.com/slekup/passport-discord-auth/assets/74949101/bbb66d22-c1be-46d4-8c6a-b3f31b4fe318)

**Comment by slekup** [comment]
Stale
